### ISSUE TITLE
Generic test: check all CPUs are brought up successfully (bootrr?)

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#674] opened 2021-05-21 12:55 UTC
For example, this board only has the big cluster working and not the little one: https://linux.kernelci.org/test/plan/id/609092c1abc2cef5c6c917d0/

but it's not reported as an error because the kernel only prints warnings

**Comment by gctucker** [comment] 2021-05-25 14:00
Duplicate of #682 as this is one particular test case that can be done while extending baseline test support.

**Closed by gctucker** 2021-05-25 14:00 UTC
Labels: native
