### ISSUE TITLE
CIP: resolve / filter remaining issues of 4.4 branch

### ISSUE THREAD

**Issue by jan-kiszka** [kernelci/kernelci-core#1053] opened 2022-02-24 13:44 UTC
See https://linux.kernelci.org/build/stable-rc/branch/linux-4.4.y/kernel/v4.4.302/ or also maintainer staging branches like https://linux.kernelci.org/build/cip-gitlab/branch/ci%2Fpavel%2Flinux-test/kernel/v4.4.302-1101-gc2ab5f3d8331/

@aliceinwire @patersonc

**Comment by patersonc** [comment] 2022-02-25 09:00
Hi @jan-kiszka 

Could you add some more detail on what the issue/request actually is?

Thanks, Chris

**Comment by jan-kiszka** [comment] 2022-02-25 09:16
As we discussed yesterday: either resolve the cited errors or drop those configs.

**Comment by gctucker** [comment] 2022-02-25 09:22
Others have mentioned before the fact that some builds are failing on old stable branches and it wasn't worth keeping them. If you think they can be fixed then great, otherwise we can add a `blocklist` filter in the build configs YAML.  I think the same issues are on the stable queues, stable-rc and stable trees for 4.4 and probably 4.9 too.

A long-term solution for that is to determine new regressions from one stable release to the next, as that would be the basis for sending automated email reports for stable review threads.  These are the ones that really have to get fixed in order to keep the same quality level in the code.  Then new regressions could be highlighted on the web UI rather than all regressions.  This would apply to tests too, or any result in KernelCI.  The advantage would be to not require any manual maintenance about things to report or not report.

**Comment by fbezdeka** [comment] 2022-08-16 11:07
Maybe it's time to refresh this one here. In the meantime we
- Disabled arm64 builds for the 4.4-cip tree (https://github.com/kernelci/kernelci-core/pull/1362)
- Silenced some build failures caused by invalid kernel/compiler/kconfig combinations (https://github.com/kernelci/kernelci-core/pull/1299/commits)

As already summarized in #1362, we now have the following issues for the 4.4-cip tree:

- baseline/x86_64_defconfig+x86-chromebook
  https://storage.staging.kernelci.org/cip/linux-4.4.y-cip/v4.4.302-cip70-97-g3635ffa3f2b2/x86_64/x86_64_defconfig+x86-chromebook/gcc-10/lab-collabora/baseline-hp-x360-14-G1-sona.html
  looks like the prompt was not properly detected
- baseline-cip-nfs/beaglebone-black multi_v7_defconfig
  https://storage.staging.kernelci.org/cip/linux-4.4.y-cip/v4.4.302-cip70-97-g3635ffa3f2b2/arm/multi_v7_defconfig/gcc-10/lab-broonie/baseline-cip-nfs-beaglebone-black.html
  No idea what went wrong here. Seems we reached the auto-login and tried to fire some shell commands. Unclear why a u-boot action is marked as failed here
-  kselftest-alsa/hp-x360-14-G1-sona x86_64_defconfig+x86-chromebook
  Seems like a failure in trying to get NFS rootfs mounted, no interfaces available? Missing driver?
  https://storage.staging.kernelci.org/cip/linux-4.4.y-cip/v4.4.302-cip70-97-g3635ffa3f2b2/x86_64/x86_64_defconfig+x86-chromebook/gcc-10/lab-collabora/kselftest-alsa-hp-x360-14-G1-sona.html
- ltp-fcntl-locktests/asus-C523NA-A20057-coral x86_64_defconfig+x86-chromebook
  https://storage.staging.kernelci.org/cip/linux-4.4.y-cip/v4.4.302-cip70-97-g3635ffa3f2b2/x86_64/x86_64_defconfig+x86-chromebook/gcc-10/lab-collabora/ltp-fcntl-locktests-asus-C523NA-A20057-coral.html
  Looks identical to the previous one. Missing driver?
- ltp-pty/asus-C523NA-A20057-coral x86_64_defconfig+x86-chromebook
  https://storage.staging.kernelci.org/cip/linux-4.4.y-cip/v4.4.302-cip70-97-g3635ffa3f2b2/x86_64/x86_64_defconfig+x86-chromebook/gcc-10/lab-collabora/ltp-pty-asus-C523NA-A20057-coral.html
  Looks identical to the previous one. Missing driver?

Who is able to help here? Would be nice to get the 4.4-cip tree "green".

@aliceinwire

**Comment by aliceinwire** [comment] 2022-10-20 12:48
@fbezdeka please don't check staging, check only production. https://cip.kernel.org

**Comment by fbezdeka** [comment] 2022-10-21 10:47
According to https://lists.cip-project.org/g/cip-dev/message/9797 the filtering works now. We have one SMC related issue remaining but that looks not limited to 4.4-cip at first glance. Should we close this issue now?

**Comment by aliceinwire** [comment] 2022-10-21 12:24
@fbezdeka let's check at the next CIP meeting.

**Comment by aliceinwire** [comment] 2022-12-01 12:11
closing as per decision at CIP meeting 2022/12/01

**Closed by aliceinwire** 2022-12-01 12:11 UTC
Labels: cip
